sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t davidyu2357/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true davidyu2357/docker-react npm run test